// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameStoreSystem.Web.Data;

#nullable disable

namespace VideoGameStoreSystem.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413141342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppChangeLog", b =>
                {
                    b.Property<int>("ChangeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CHANGE_LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ACTION_TYPE");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CHANGED_AT");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CHANGED_BY_USER_ID");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.HasKey("ChangeLogId")
                        .HasName("PK_CHANGE_LOGS");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("IX_CHANGE_LOGS_CHANGED_AT");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("IX_CHANGE_LOGS_CHANGED_BY_USER_ID");

                    b.ToTable("CHANGE_LOGS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("RoleId")
                        .HasName("PK_ROLES");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("IX_ROLES_ROLE_NAME");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOGIN");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("UserId")
                        .HasName("PK_USERS");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_USERS_EMAIL");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_LOGIN");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_USERS_ROLE_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CATEGORY_NAME");

                    b.HasKey("CategoryId")
                        .HasName("PK_CATEGORIES");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("IX_CATEGORIES_CATEGORY_NAME");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("CustomerId")
                        .HasName("PK_CUSTOMERS");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_CUSTOMERS_EMAIL");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_CUSTOMERS_FULL_NAME");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_CUSTOMERS_USER_ID")
                        .HasFilter("[USER_ID] IS NOT NULL");

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("COST_PRICE");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("SKU");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("STOCK_QUANTITY");

                    b.HasKey("ProductId")
                        .HasName("PK_PRODUCTS");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_PRODUCTS_CATEGORY_ID");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_PRODUCTS_PRODUCT_NAME");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_PRODUCTS_SKU");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SALE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SALE_DATE");

                    b.Property<int>("SellerUserId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_USER_ID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("SaleId")
                        .HasName("PK_SALES");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_SALES_CUSTOMER_ID");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("IX_SALES_SALE_DATE");

                    b.HasIndex("SellerUserId")
                        .HasDatabaseName("IX_SALES_SELLER_USER_ID");

                    b.ToTable("SALES");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.SaleItem", b =>
                {
                    b.Property<int>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SALE_ITEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LINE_TOTAL");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SALE_ID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("SaleItemId")
                        .HasName("PK_SALE_ITEMS");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SALE_ITEMS_PRODUCT_ID");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("IX_SALE_ITEMS_SALE_ID");

                    b.ToTable("SALE_ITEMS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUPPLIER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHONE");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SUPPLIER_NAME");

                    b.HasKey("SupplierId")
                        .HasName("PK_SUPPLIERS");

                    b.HasIndex("SupplierName")
                        .HasDatabaseName("IX_SUPPLIERS_SUPPLIER_NAME");

                    b.ToTable("SUPPLIERS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Supply", b =>
                {
                    b.Property<int>("SupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUPPLY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyId"));

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SUPPLIER_ID");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SUPPLY_DATE");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("SupplyId")
                        .HasName("PK_SUPPLIES");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_SUPPLIES_SUPPLIER_ID");

                    b.HasIndex("SupplyDate")
                        .HasDatabaseName("IX_SUPPLIES_SUPPLY_DATE");

                    b.ToTable("SUPPLIES");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.SupplyItem", b =>
                {
                    b.Property<int>("SupplyItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUPPLY_ITEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int")
                        .HasColumnName("SUPPLY_ID");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UNIT_COST");

                    b.HasKey("SupplyItemId")
                        .HasName("PK_SUPPLY_ITEMS");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SUPPLY_ITEMS_PRODUCT_ID");

                    b.HasIndex("SupplyId")
                        .HasDatabaseName("IX_SUPPLY_ITEMS_SUPPLY_ID");

                    b.ToTable("SUPPLY_ITEMS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.WriteOff", b =>
                {
                    b.Property<int>("WriteOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WRITE_OFF_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WriteOffId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CREATED_BY_USER_ID");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("REASON");

                    b.Property<DateTime>("WriteOffDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("WRITE_OFF_DATE");

                    b.HasKey("WriteOffId")
                        .HasName("PK_WRITE_OFFS");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_WRITE_OFFS_CREATED_BY_USER_ID");

                    b.HasIndex("WriteOffDate")
                        .HasDatabaseName("IX_WRITE_OFFS_WRITE_OFF_DATE");

                    b.ToTable("WRITE_OFFS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.WriteOffItem", b =>
                {
                    b.Property<int>("WriteOffItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WRITE_OFF_ITEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WriteOffItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("WriteOffId")
                        .HasColumnType("int")
                        .HasColumnName("WRITE_OFF_ID");

                    b.HasKey("WriteOffItemId")
                        .HasName("PK_WRITE_OFF_ITEMS");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_WRITE_OFF_ITEMS_PRODUCT_ID");

                    b.HasIndex("WriteOffId")
                        .HasDatabaseName("IX_WRITE_OFF_ITEMS_WRITE_OFF_ID");

                    b.ToTable("WRITE_OFF_ITEMS");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppChangeLog", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.AppUser", "ChangedByUser")
                        .WithMany("Changes")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_CHANGE_LOGS_USERS_CHANGED_BY_USER_ID");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppUser", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_USERS_ROLES_ROLE_ID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Customer", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.AppUser", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("VideoGameStoreSystem.Web.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_CUSTOMERS_USERS_USER_ID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Product", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTS_CATEGORIES_CATEGORY_ID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Sale", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SALES_CUSTOMERS_CUSTOMER_ID");

                    b.HasOne("VideoGameStoreSystem.Web.Models.AppUser", "SellerUser")
                        .WithMany("SalesAsSeller")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALES_USERS_SELLER_USER_ID");

                    b.Navigation("Customer");

                    b.Navigation("SellerUser");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.SaleItem", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SALE_ITEMS_PRODUCTS_PRODUCT_ID");

                    b.HasOne("VideoGameStoreSystem.Web.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SALE_ITEMS_SALES_SALE_ID");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Supply", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Supplier", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SUPPLIES_SUPPLIERS_SUPPLIER_ID");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.SupplyItem", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Product", "Product")
                        .WithMany("SupplyItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SUPPLY_ITEMS_PRODUCTS_PRODUCT_ID");

                    b.HasOne("VideoGameStoreSystem.Web.Models.Supply", "Supply")
                        .WithMany("Items")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SUPPLY_ITEMS_SUPPLIES_SUPPLY_ID");

                    b.Navigation("Product");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.WriteOff", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.AppUser", "CreatedByUser")
                        .WithMany("WriteOffsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WRITE_OFFS_USERS_CREATED_BY_USER_ID");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.WriteOffItem", b =>
                {
                    b.HasOne("VideoGameStoreSystem.Web.Models.Product", "Product")
                        .WithMany("WriteOffItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WRITE_OFF_ITEMS_PRODUCTS_PRODUCT_ID");

                    b.HasOne("VideoGameStoreSystem.Web.Models.WriteOff", "WriteOff")
                        .WithMany("Items")
                        .HasForeignKey("WriteOffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WRITE_OFF_ITEMS_WRITE_OFFS_WRITE_OFF_ID");

                    b.Navigation("Product");

                    b.Navigation("WriteOff");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.AppUser", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("CustomerProfile");

                    b.Navigation("SalesAsSeller");

                    b.Navigation("WriteOffsCreated");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Product", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("SupplyItems");

                    b.Navigation("WriteOffItems");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Supplier", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.Supply", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VideoGameStoreSystem.Web.Models.WriteOff", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
