IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [CATEGORIES] (
    [CATEGORY_ID] int NOT NULL IDENTITY,
    [CATEGORY_NAME] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_CATEGORIES] PRIMARY KEY ([CATEGORY_ID])
);
GO

CREATE TABLE [ROLES] (
    [ROLE_ID] int NOT NULL IDENTITY,
    [ROLE_NAME] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_ROLES] PRIMARY KEY ([ROLE_ID])
);
GO

CREATE TABLE [SUPPLIERS] (
    [SUPPLIER_ID] int NOT NULL IDENTITY,
    [SUPPLIER_NAME] nvarchar(150) NOT NULL,
    [PHONE] nvarchar(50) NULL,
    [EMAIL] nvarchar(150) NULL,
    CONSTRAINT [PK_SUPPLIERS] PRIMARY KEY ([SUPPLIER_ID])
);
GO

CREATE TABLE [PRODUCTS] (
    [PRODUCT_ID] int NOT NULL IDENTITY,
    [PRODUCT_NAME] nvarchar(200) NOT NULL,
    [CATEGORY_ID] int NOT NULL,
    [SKU] nvarchar(40) NOT NULL,
    [DESCRIPTION] nvarchar(2000) NULL,
    [PRICE] decimal(18,2) NOT NULL,
    [COST_PRICE] decimal(18,2) NOT NULL,
    [STOCK_QUANTITY] int NOT NULL,
    [IS_ACTIVE] bit NOT NULL,
    CONSTRAINT [PK_PRODUCTS] PRIMARY KEY ([PRODUCT_ID]),
    CONSTRAINT [FK_PRODUCTS_CATEGORIES_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [CATEGORIES] ([CATEGORY_ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [USERS] (
    [USER_ID] int NOT NULL IDENTITY,
    [LOGIN] nvarchar(50) NOT NULL,
    [PASSWORD_HASH] nvarchar(512) NOT NULL,
    [FULL_NAME] nvarchar(150) NOT NULL,
    [EMAIL] nvarchar(150) NOT NULL,
    [ROLE_ID] int NOT NULL,
    [IS_ACTIVE] bit NOT NULL,
    [CREATED_AT] datetime2 NOT NULL,
    CONSTRAINT [PK_USERS] PRIMARY KEY ([USER_ID]),
    CONSTRAINT [FK_USERS_ROLES_ROLE_ID] FOREIGN KEY ([ROLE_ID]) REFERENCES [ROLES] ([ROLE_ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [SUPPLIES] (
    [SUPPLY_ID] int NOT NULL IDENTITY,
    [SUPPLY_DATE] datetime2 NOT NULL,
    [SUPPLIER_ID] int NOT NULL,
    [TOTAL_AMOUNT] decimal(18,2) NOT NULL,
    CONSTRAINT [PK_SUPPLIES] PRIMARY KEY ([SUPPLY_ID]),
    CONSTRAINT [FK_SUPPLIES_SUPPLIERS_SUPPLIER_ID] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [SUPPLIERS] ([SUPPLIER_ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [CHANGE_LOGS] (
    [CHANGE_LOG_ID] int NOT NULL IDENTITY,
    [ENTITY_NAME] nvarchar(150) NOT NULL,
    [ENTITY_ID] nvarchar(150) NOT NULL,
    [ACTION_TYPE] nvarchar(30) NOT NULL,
    [OLD_VALUES] nvarchar(max) NULL,
    [NEW_VALUES] nvarchar(max) NULL,
    [CHANGED_AT] datetime2 NOT NULL,
    [CHANGED_BY_USER_ID] int NULL,
    CONSTRAINT [PK_CHANGE_LOGS] PRIMARY KEY ([CHANGE_LOG_ID]),
    CONSTRAINT [FK_CHANGE_LOGS_USERS_CHANGED_BY_USER_ID] FOREIGN KEY ([CHANGED_BY_USER_ID]) REFERENCES [USERS] ([USER_ID]) ON DELETE SET NULL
);
GO

CREATE TABLE [CUSTOMERS] (
    [CUSTOMER_ID] int NOT NULL IDENTITY,
    [FULL_NAME] nvarchar(150) NOT NULL,
    [PHONE] nvarchar(50) NULL,
    [EMAIL] nvarchar(150) NULL,
    [USER_ID] int NULL,
    CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY ([CUSTOMER_ID]),
    CONSTRAINT [FK_CUSTOMERS_USERS_USER_ID] FOREIGN KEY ([USER_ID]) REFERENCES [USERS] ([USER_ID]) ON DELETE SET NULL
);
GO

CREATE TABLE [WRITE_OFFS] (
    [WRITE_OFF_ID] int NOT NULL IDENTITY,
    [WRITE_OFF_DATE] datetime2 NOT NULL,
    [REASON] nvarchar(300) NOT NULL,
    [CREATED_BY_USER_ID] int NOT NULL,
    CONSTRAINT [PK_WRITE_OFFS] PRIMARY KEY ([WRITE_OFF_ID]),
    CONSTRAINT [FK_WRITE_OFFS_USERS_CREATED_BY_USER_ID] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [USERS] ([USER_ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [SUPPLY_ITEMS] (
    [SUPPLY_ITEM_ID] int NOT NULL IDENTITY,
    [SUPPLY_ID] int NOT NULL,
    [PRODUCT_ID] int NOT NULL,
    [QUANTITY] int NOT NULL,
    [UNIT_COST] decimal(18,2) NOT NULL,
    CONSTRAINT [PK_SUPPLY_ITEMS] PRIMARY KEY ([SUPPLY_ITEM_ID]),
    CONSTRAINT [FK_SUPPLY_ITEMS_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCTS] ([PRODUCT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SUPPLY_ITEMS_SUPPLIES_SUPPLY_ID] FOREIGN KEY ([SUPPLY_ID]) REFERENCES [SUPPLIES] ([SUPPLY_ID]) ON DELETE CASCADE
);
GO

CREATE TABLE [SALES] (
    [SALE_ID] int NOT NULL IDENTITY,
    [SALE_DATE] datetime2 NOT NULL,
    [CUSTOMER_ID] int NULL,
    [SELLER_USER_ID] int NOT NULL,
    [TOTAL_AMOUNT] decimal(18,2) NOT NULL,
    CONSTRAINT [PK_SALES] PRIMARY KEY ([SALE_ID]),
    CONSTRAINT [FK_SALES_CUSTOMERS_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [CUSTOMERS] ([CUSTOMER_ID]) ON DELETE SET NULL,
    CONSTRAINT [FK_SALES_USERS_SELLER_USER_ID] FOREIGN KEY ([SELLER_USER_ID]) REFERENCES [USERS] ([USER_ID]) ON DELETE NO ACTION
);
GO

CREATE TABLE [WRITE_OFF_ITEMS] (
    [WRITE_OFF_ITEM_ID] int NOT NULL IDENTITY,
    [WRITE_OFF_ID] int NOT NULL,
    [PRODUCT_ID] int NOT NULL,
    [QUANTITY] int NOT NULL,
    CONSTRAINT [PK_WRITE_OFF_ITEMS] PRIMARY KEY ([WRITE_OFF_ITEM_ID]),
    CONSTRAINT [FK_WRITE_OFF_ITEMS_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCTS] ([PRODUCT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_WRITE_OFF_ITEMS_WRITE_OFFS_WRITE_OFF_ID] FOREIGN KEY ([WRITE_OFF_ID]) REFERENCES [WRITE_OFFS] ([WRITE_OFF_ID]) ON DELETE CASCADE
);
GO

CREATE TABLE [SALE_ITEMS] (
    [SALE_ITEM_ID] int NOT NULL IDENTITY,
    [SALE_ID] int NOT NULL,
    [PRODUCT_ID] int NOT NULL,
    [QUANTITY] int NOT NULL,
    [UNIT_PRICE] decimal(18,2) NOT NULL,
    [LINE_TOTAL] decimal(18,2) NOT NULL,
    CONSTRAINT [PK_SALE_ITEMS] PRIMARY KEY ([SALE_ITEM_ID]),
    CONSTRAINT [FK_SALE_ITEMS_PRODUCTS_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCTS] ([PRODUCT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SALE_ITEMS_SALES_SALE_ID] FOREIGN KEY ([SALE_ID]) REFERENCES [SALES] ([SALE_ID]) ON DELETE CASCADE
);
GO

CREATE UNIQUE INDEX [IX_CATEGORIES_CATEGORY_NAME] ON [CATEGORIES] ([CATEGORY_NAME]);
GO

CREATE INDEX [IX_CHANGE_LOGS_CHANGED_AT] ON [CHANGE_LOGS] ([CHANGED_AT]);
GO

CREATE INDEX [IX_CHANGE_LOGS_CHANGED_BY_USER_ID] ON [CHANGE_LOGS] ([CHANGED_BY_USER_ID]);
GO

CREATE INDEX [IX_CUSTOMERS_EMAIL] ON [CUSTOMERS] ([EMAIL]);
GO

CREATE INDEX [IX_CUSTOMERS_FULL_NAME] ON [CUSTOMERS] ([FULL_NAME]);
GO

CREATE UNIQUE INDEX [IX_CUSTOMERS_USER_ID] ON [CUSTOMERS] ([USER_ID]) WHERE [USER_ID] IS NOT NULL;
GO

CREATE INDEX [IX_PRODUCTS_CATEGORY_ID] ON [PRODUCTS] ([CATEGORY_ID]);
GO

CREATE INDEX [IX_PRODUCTS_PRODUCT_NAME] ON [PRODUCTS] ([PRODUCT_NAME]);
GO

CREATE UNIQUE INDEX [IX_PRODUCTS_SKU] ON [PRODUCTS] ([SKU]);
GO

CREATE UNIQUE INDEX [IX_ROLES_ROLE_NAME] ON [ROLES] ([ROLE_NAME]);
GO

CREATE INDEX [IX_SALE_ITEMS_PRODUCT_ID] ON [SALE_ITEMS] ([PRODUCT_ID]);
GO

CREATE INDEX [IX_SALE_ITEMS_SALE_ID] ON [SALE_ITEMS] ([SALE_ID]);
GO

CREATE INDEX [IX_SALES_CUSTOMER_ID] ON [SALES] ([CUSTOMER_ID]);
GO

CREATE INDEX [IX_SALES_SALE_DATE] ON [SALES] ([SALE_DATE]);
GO

CREATE INDEX [IX_SALES_SELLER_USER_ID] ON [SALES] ([SELLER_USER_ID]);
GO

CREATE INDEX [IX_SUPPLIERS_SUPPLIER_NAME] ON [SUPPLIERS] ([SUPPLIER_NAME]);
GO

CREATE INDEX [IX_SUPPLIES_SUPPLIER_ID] ON [SUPPLIES] ([SUPPLIER_ID]);
GO

CREATE INDEX [IX_SUPPLIES_SUPPLY_DATE] ON [SUPPLIES] ([SUPPLY_DATE]);
GO

CREATE INDEX [IX_SUPPLY_ITEMS_PRODUCT_ID] ON [SUPPLY_ITEMS] ([PRODUCT_ID]);
GO

CREATE INDEX [IX_SUPPLY_ITEMS_SUPPLY_ID] ON [SUPPLY_ITEMS] ([SUPPLY_ID]);
GO

CREATE INDEX [IX_USERS_EMAIL] ON [USERS] ([EMAIL]);
GO

CREATE UNIQUE INDEX [IX_USERS_LOGIN] ON [USERS] ([LOGIN]);
GO

CREATE INDEX [IX_USERS_ROLE_ID] ON [USERS] ([ROLE_ID]);
GO

CREATE INDEX [IX_WRITE_OFF_ITEMS_PRODUCT_ID] ON [WRITE_OFF_ITEMS] ([PRODUCT_ID]);
GO

CREATE INDEX [IX_WRITE_OFF_ITEMS_WRITE_OFF_ID] ON [WRITE_OFF_ITEMS] ([WRITE_OFF_ID]);
GO

CREATE INDEX [IX_WRITE_OFFS_CREATED_BY_USER_ID] ON [WRITE_OFFS] ([CREATED_BY_USER_ID]);
GO

CREATE INDEX [IX_WRITE_OFFS_WRITE_OFF_DATE] ON [WRITE_OFFS] ([WRITE_OFF_DATE]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260413141342_InitialCreate', N'8.0.15');
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

ALTER TABLE [CHANGE_LOGS] DROP CONSTRAINT [FK_CHANGE_LOGS_USERS_CHANGED_BY_USER_ID];
GO

ALTER TABLE [CUSTOMERS] DROP CONSTRAINT [FK_CUSTOMERS_USERS_USER_ID];
GO

ALTER TABLE [PRODUCTS] DROP CONSTRAINT [FK_PRODUCTS_CATEGORIES_CATEGORY_ID];
GO

ALTER TABLE [SALE_ITEMS] DROP CONSTRAINT [FK_SALE_ITEMS_PRODUCTS_PRODUCT_ID];
GO

ALTER TABLE [SALE_ITEMS] DROP CONSTRAINT [FK_SALE_ITEMS_SALES_SALE_ID];
GO

ALTER TABLE [SALES] DROP CONSTRAINT [FK_SALES_CUSTOMERS_CUSTOMER_ID];
GO

ALTER TABLE [SALES] DROP CONSTRAINT [FK_SALES_USERS_SELLER_USER_ID];
GO

ALTER TABLE [SUPPLIES] DROP CONSTRAINT [FK_SUPPLIES_SUPPLIERS_SUPPLIER_ID];
GO

ALTER TABLE [SUPPLY_ITEMS] DROP CONSTRAINT [FK_SUPPLY_ITEMS_PRODUCTS_PRODUCT_ID];
GO

ALTER TABLE [SUPPLY_ITEMS] DROP CONSTRAINT [FK_SUPPLY_ITEMS_SUPPLIES_SUPPLY_ID];
GO

ALTER TABLE [USERS] DROP CONSTRAINT [FK_USERS_ROLES_ROLE_ID];
GO

ALTER TABLE [WRITE_OFF_ITEMS] DROP CONSTRAINT [FK_WRITE_OFF_ITEMS_PRODUCTS_PRODUCT_ID];
GO

ALTER TABLE [WRITE_OFF_ITEMS] DROP CONSTRAINT [FK_WRITE_OFF_ITEMS_WRITE_OFFS_WRITE_OFF_ID];
GO

ALTER TABLE [WRITE_OFFS] DROP CONSTRAINT [FK_WRITE_OFFS_USERS_CREATED_BY_USER_ID];
GO

ALTER TABLE [WRITE_OFFS] DROP CONSTRAINT [PK_WRITE_OFFS];
GO

ALTER TABLE [WRITE_OFF_ITEMS] DROP CONSTRAINT [PK_WRITE_OFF_ITEMS];
GO

ALTER TABLE [USERS] DROP CONSTRAINT [PK_USERS];
GO

ALTER TABLE [SUPPLY_ITEMS] DROP CONSTRAINT [PK_SUPPLY_ITEMS];
GO

ALTER TABLE [SUPPLIES] DROP CONSTRAINT [PK_SUPPLIES];
GO

ALTER TABLE [SUPPLIERS] DROP CONSTRAINT [PK_SUPPLIERS];
GO

ALTER TABLE [SALES] DROP CONSTRAINT [PK_SALES];
GO

ALTER TABLE [SALE_ITEMS] DROP CONSTRAINT [PK_SALE_ITEMS];
GO

ALTER TABLE [ROLES] DROP CONSTRAINT [PK_ROLES];
GO

ALTER TABLE [PRODUCTS] DROP CONSTRAINT [PK_PRODUCTS];
GO

ALTER TABLE [CUSTOMERS] DROP CONSTRAINT [PK_CUSTOMERS];
GO

ALTER TABLE [CHANGE_LOGS] DROP CONSTRAINT [PK_CHANGE_LOGS];
GO

ALTER TABLE [CATEGORIES] DROP CONSTRAINT [PK_CATEGORIES];
GO

EXEC sp_rename N'[WRITE_OFFS]', N'WRITE_OFF';
GO

EXEC sp_rename N'[WRITE_OFF_ITEMS]', N'WRITE_OFF_ITEM';
GO

EXEC sp_rename N'[USERS]', N'APP_USER';
GO

EXEC sp_rename N'[SUPPLY_ITEMS]', N'SUPPLY_ITEM';
GO

EXEC sp_rename N'[SUPPLIES]', N'SUPPLY';
GO

EXEC sp_rename N'[SUPPLIERS]', N'SUPPLIER';
GO

EXEC sp_rename N'[SALES]', N'SALE';
GO

EXEC sp_rename N'[SALE_ITEMS]', N'SALE_ITEM';
GO

EXEC sp_rename N'[ROLES]', N'APP_ROLE';
GO

EXEC sp_rename N'[PRODUCTS]', N'PRODUCT';
GO

EXEC sp_rename N'[CUSTOMERS]', N'CUSTOMER';
GO

EXEC sp_rename N'[CHANGE_LOGS]', N'APP_CHANGE_LOG';
GO

EXEC sp_rename N'[CATEGORIES]', N'CATEGORY';
GO

EXEC sp_rename N'[WRITE_OFF].[IX_WRITE_OFFS_WRITE_OFF_DATE]', N'IX_WRITE_OFF_WRITE_OFF_DATE', N'INDEX';
GO

EXEC sp_rename N'[WRITE_OFF].[IX_WRITE_OFFS_CREATED_BY_USER_ID]', N'IX_WRITE_OFF_CREATED_BY_USER_ID', N'INDEX';
GO

EXEC sp_rename N'[WRITE_OFF_ITEM].[IX_WRITE_OFF_ITEMS_WRITE_OFF_ID]', N'IX_WRITE_OFF_ITEM_WRITE_OFF_ID', N'INDEX';
GO

EXEC sp_rename N'[WRITE_OFF_ITEM].[IX_WRITE_OFF_ITEMS_PRODUCT_ID]', N'IX_WRITE_OFF_ITEM_PRODUCT_ID', N'INDEX';
GO

EXEC sp_rename N'[APP_USER].[IX_USERS_ROLE_ID]', N'IX_APP_USER_ROLE_ID', N'INDEX';
GO

EXEC sp_rename N'[APP_USER].[IX_USERS_LOGIN]', N'IX_APP_USER_LOGIN', N'INDEX';
GO

EXEC sp_rename N'[APP_USER].[IX_USERS_EMAIL]', N'IX_APP_USER_EMAIL', N'INDEX';
GO

EXEC sp_rename N'[SUPPLY_ITEM].[IX_SUPPLY_ITEMS_SUPPLY_ID]', N'IX_SUPPLY_ITEM_SUPPLY_ID', N'INDEX';
GO

EXEC sp_rename N'[SUPPLY_ITEM].[IX_SUPPLY_ITEMS_PRODUCT_ID]', N'IX_SUPPLY_ITEM_PRODUCT_ID', N'INDEX';
GO

EXEC sp_rename N'[SUPPLY].[IX_SUPPLIES_SUPPLY_DATE]', N'IX_SUPPLY_SUPPLY_DATE', N'INDEX';
GO

EXEC sp_rename N'[SUPPLY].[IX_SUPPLIES_SUPPLIER_ID]', N'IX_SUPPLY_SUPPLIER_ID', N'INDEX';
GO

EXEC sp_rename N'[SUPPLIER].[IX_SUPPLIERS_SUPPLIER_NAME]', N'IX_SUPPLIER_SUPPLIER_NAME', N'INDEX';
GO

EXEC sp_rename N'[SALE].[IX_SALES_SELLER_USER_ID]', N'IX_SALE_SELLER_USER_ID', N'INDEX';
GO

EXEC sp_rename N'[SALE].[IX_SALES_SALE_DATE]', N'IX_SALE_SALE_DATE', N'INDEX';
GO

EXEC sp_rename N'[SALE].[IX_SALES_CUSTOMER_ID]', N'IX_SALE_CUSTOMER_ID', N'INDEX';
GO

EXEC sp_rename N'[SALE_ITEM].[IX_SALE_ITEMS_SALE_ID]', N'IX_SALE_ITEM_SALE_ID', N'INDEX';
GO

EXEC sp_rename N'[SALE_ITEM].[IX_SALE_ITEMS_PRODUCT_ID]', N'IX_SALE_ITEM_PRODUCT_ID', N'INDEX';
GO

EXEC sp_rename N'[APP_ROLE].[IX_ROLES_ROLE_NAME]', N'IX_APP_ROLE_ROLE_NAME', N'INDEX';
GO

EXEC sp_rename N'[PRODUCT].[IX_PRODUCTS_SKU]', N'IX_PRODUCT_SKU', N'INDEX';
GO

EXEC sp_rename N'[PRODUCT].[IX_PRODUCTS_PRODUCT_NAME]', N'IX_PRODUCT_PRODUCT_NAME', N'INDEX';
GO

EXEC sp_rename N'[PRODUCT].[IX_PRODUCTS_CATEGORY_ID]', N'IX_PRODUCT_CATEGORY_ID', N'INDEX';
GO

EXEC sp_rename N'[CUSTOMER].[IX_CUSTOMERS_USER_ID]', N'IX_CUSTOMER_USER_ID', N'INDEX';
GO

EXEC sp_rename N'[CUSTOMER].[IX_CUSTOMERS_FULL_NAME]', N'IX_CUSTOMER_FULL_NAME', N'INDEX';
GO

EXEC sp_rename N'[CUSTOMER].[IX_CUSTOMERS_EMAIL]', N'IX_CUSTOMER_EMAIL', N'INDEX';
GO

EXEC sp_rename N'[APP_CHANGE_LOG].[IX_CHANGE_LOGS_CHANGED_BY_USER_ID]', N'IX_APP_CHANGE_LOG_CHANGED_BY_USER_ID', N'INDEX';
GO

EXEC sp_rename N'[APP_CHANGE_LOG].[IX_CHANGE_LOGS_CHANGED_AT]', N'IX_APP_CHANGE_LOG_CHANGED_AT', N'INDEX';
GO

EXEC sp_rename N'[CATEGORY].[IX_CATEGORIES_CATEGORY_NAME]', N'IX_CATEGORY_CATEGORY_NAME', N'INDEX';
GO

ALTER TABLE [WRITE_OFF] ADD CONSTRAINT [PK_WRITE_OFF] PRIMARY KEY ([WRITE_OFF_ID]);
GO

ALTER TABLE [WRITE_OFF_ITEM] ADD CONSTRAINT [PK_WRITE_OFF_ITEM] PRIMARY KEY ([WRITE_OFF_ITEM_ID]);
GO

ALTER TABLE [APP_USER] ADD CONSTRAINT [PK_APP_USER] PRIMARY KEY ([USER_ID]);
GO

ALTER TABLE [SUPPLY_ITEM] ADD CONSTRAINT [PK_SUPPLY_ITEM] PRIMARY KEY ([SUPPLY_ITEM_ID]);
GO

ALTER TABLE [SUPPLY] ADD CONSTRAINT [PK_SUPPLY] PRIMARY KEY ([SUPPLY_ID]);
GO

ALTER TABLE [SUPPLIER] ADD CONSTRAINT [PK_SUPPLIER] PRIMARY KEY ([SUPPLIER_ID]);
GO

ALTER TABLE [SALE] ADD CONSTRAINT [PK_SALE] PRIMARY KEY ([SALE_ID]);
GO

ALTER TABLE [SALE_ITEM] ADD CONSTRAINT [PK_SALE_ITEM] PRIMARY KEY ([SALE_ITEM_ID]);
GO

ALTER TABLE [APP_ROLE] ADD CONSTRAINT [PK_APP_ROLE] PRIMARY KEY ([ROLE_ID]);
GO

ALTER TABLE [PRODUCT] ADD CONSTRAINT [PK_PRODUCT] PRIMARY KEY ([PRODUCT_ID]);
GO

ALTER TABLE [CUSTOMER] ADD CONSTRAINT [PK_CUSTOMER] PRIMARY KEY ([CUSTOMER_ID]);
GO

ALTER TABLE [APP_CHANGE_LOG] ADD CONSTRAINT [PK_APP_CHANGE_LOG] PRIMARY KEY ([CHANGE_LOG_ID]);
GO

ALTER TABLE [CATEGORY] ADD CONSTRAINT [PK_CATEGORY] PRIMARY KEY ([CATEGORY_ID]);
GO

ALTER TABLE [APP_CHANGE_LOG] ADD CONSTRAINT [FK_APP_CHANGE_LOG_APP_USER_CHANGED_BY_USER_ID] FOREIGN KEY ([CHANGED_BY_USER_ID]) REFERENCES [APP_USER] ([USER_ID]) ON DELETE SET NULL;
GO

ALTER TABLE [APP_USER] ADD CONSTRAINT [FK_APP_USER_APP_ROLE_ROLE_ID] FOREIGN KEY ([ROLE_ID]) REFERENCES [APP_ROLE] ([ROLE_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [CUSTOMER] ADD CONSTRAINT [FK_CUSTOMER_APP_USER_USER_ID] FOREIGN KEY ([USER_ID]) REFERENCES [APP_USER] ([USER_ID]) ON DELETE SET NULL;
GO

ALTER TABLE [PRODUCT] ADD CONSTRAINT [FK_PRODUCT_CATEGORY_CATEGORY_ID] FOREIGN KEY ([CATEGORY_ID]) REFERENCES [CATEGORY] ([CATEGORY_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [SALE] ADD CONSTRAINT [FK_SALE_APP_USER_SELLER_USER_ID] FOREIGN KEY ([SELLER_USER_ID]) REFERENCES [APP_USER] ([USER_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [SALE] ADD CONSTRAINT [FK_SALE_CUSTOMER_CUSTOMER_ID] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [CUSTOMER] ([CUSTOMER_ID]) ON DELETE SET NULL;
GO

ALTER TABLE [SALE_ITEM] ADD CONSTRAINT [FK_SALE_ITEM_PRODUCT_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [SALE_ITEM] ADD CONSTRAINT [FK_SALE_ITEM_SALE_SALE_ID] FOREIGN KEY ([SALE_ID]) REFERENCES [SALE] ([SALE_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [SUPPLY] ADD CONSTRAINT [FK_SUPPLY_SUPPLIER_SUPPLIER_ID] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [SUPPLIER] ([SUPPLIER_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [SUPPLY_ITEM] ADD CONSTRAINT [FK_SUPPLY_ITEM_PRODUCT_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [SUPPLY_ITEM] ADD CONSTRAINT [FK_SUPPLY_ITEM_SUPPLY_SUPPLY_ID] FOREIGN KEY ([SUPPLY_ID]) REFERENCES [SUPPLY] ([SUPPLY_ID]) ON DELETE CASCADE;
GO

ALTER TABLE [WRITE_OFF] ADD CONSTRAINT [FK_WRITE_OFF_APP_USER_CREATED_BY_USER_ID] FOREIGN KEY ([CREATED_BY_USER_ID]) REFERENCES [APP_USER] ([USER_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [WRITE_OFF_ITEM] ADD CONSTRAINT [FK_WRITE_OFF_ITEM_PRODUCT_PRODUCT_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCT] ([PRODUCT_ID]) ON DELETE NO ACTION;
GO

ALTER TABLE [WRITE_OFF_ITEM] ADD CONSTRAINT [FK_WRITE_OFF_ITEM_WRITE_OFF_WRITE_OFF_ID] FOREIGN KEY ([WRITE_OFF_ID]) REFERENCES [WRITE_OFF] ([WRITE_OFF_ID]) ON DELETE CASCADE;
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260413141537_RenameTablesToAcademicNames', N'8.0.15');
GO

COMMIT;
GO

